=== ferrumfix/ferrumfix/crates/fefix/resources/repositories/fix_repository_2010_edition_20140507/Unified/FixRepositoryMeta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="FIX_REPOSITORY_METADATA">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ELEMENTS">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="ELEMENT">
								<xs:complexType>
									<xs:attribute name="name"/>
									<xs:attribute name="pk_name"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ferrumfix/ferrumfix/examples/hello/resources/repositories/fix_repository_2010_edition_20140507/Unified/FIXRepositoryMetadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- xsi:noNamespaceSchemaLocation="FixRepositoryMeta.xsd" --> 
<FIX_REPOSITORY_METADATA  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ELEMENTS>	
		<ELEMENT name="fix" pk_name="version"/>
		<ELEMENT name="datatype" pk_name="typeName"/>		
		<ELEMENT name="field" pk_name="id"/>	
		<ELEMENT name="value" pk_name="enum"/>	
		<ELEMENT name="component" pk_name="id"/>	
		<ELEMENT name="message" pk_name="id"/>													
	</ELEMENTS>
</FIX_REPOSITORY_METADATA>
